### PR TITLE
Support Round Frame

### PR DESCRIPTION
**Pull request by hearsilent**
Many apps both support rectangle and round profile photo,
so this pull request just show the round frame when crop preview.

Not output round photo.

### CODE REVIEW

**Comment by shliama** [comment]
@hearsilent 
Hey, as I posted in https://github.com/Yalantis/uCrop/issues/4
The feature is ready and will be shipped with next update soon.

I want to clarify more on your pull-request. Again, your approach is not efficient, drawing a Bitmap each time is excessive.
You could achieve the same behaviour in just three lines of code

1. Create Path object with circle in it 

mCircularPath.addOval(mCropViewRect, Path.Direction.CW);

2. clip canvas around this circle 

canvas.clipPath(mCircularPath, Region.Op.DIFFERENCE); 

3. draw color

canvas.drawColor(mDimmedColor);

Or just check the implementation when the code is updated.

**Comment by hearsilent** [comment]
@shliama 

Got it!
But you say "this won't properly work on number of devices with HW acceleration enabled",
how to fix it !?

**Comment by shliama** [comment]
Yep, that's a bummer. That's why I divided CropImageView logic and extracted crop overlay (frame, guidelines etc) into another view that is on top of ImageView.
So I was able to set view type to Software.

**Comment by hearsilent** [comment]
Cool, thank you all.

**Comment by shliama** [comment]
@hearsilent @devflow please check the latest version of uCrop.

Use 
```java
UCrop.Options options = new Options();
options.setOvalDimmedLayer(true);
uCrop.withOptions(options);
```

to achieve circular profile. Checkout other Options methods to configure other things.

**Comment by ImYoungUn** [comment]
image
 is it usable now? I can't find the method "setOvalDimmedLayer()"... I'm using 2.2.1 version

**Comment by ImYoungUn** [comment]
@shliama 
image

is it usable now? I can't find the method "setOvalDimmedLayer()"... I'm using 2.2.1 version

**Comment by ImYoungUn** [comment]
#189 In this answer, does it means the function was deleted and should I use another library to crop with circle shape, not this library?

**Comment by hearsilent** [comment]
@ImYoungUn It's change to `setCircleDimmedLayer`. Try it!

**Pull request closed without merging**
