### PR TITLE
Dynamic UI colors

### PR DESCRIPTION
**Pull request by timkoers**
You can change the UI color of the UI element with their respective method on the Ucrop Options, if left empty, the default colors will be used. Tested and confirmed working. The sample app is also updated.

### CODE REVIEW

**Comment by timkoers** [comment]
I found one thing that I missed out to color. I will fix that today

**Comment by shliama** [comment]
@timkoers Hi and thanks for contribution :+1: I'll definitely accept this one when you add above mentioned fix. Then I'll add a couple things and update the maven repo.

**Comment by timkoers** [comment]
@oleksii I am back home around 2 om to I'll made the changes.

Thanks


Van: Oleksii <notifications@github.com>
verzonden: 16 feb. 2016 10:11
Aan: Yalantis/uCrop
Cc: timkoers
Onderwerp: Re: [uCrop] Dynamic UI colors (#33)

@timkoers Hi and thanks for contribution :+1: I'll definitely accept this one when you add above mentioned fix. Then I'll add a couple things and update the maven repo.

---

**Comment by timkoers** [comment]
@shliama Can I safely assume that the color of the Toolbar text can be the 'normal' not selected color of the UI elements?

**Comment by shliama** [comment]
@timkoers yes, as long as default values match our Activity design.

**Comment by timkoers** [comment]
@shliama The default values will be set when the Activity starts, when the OptionsBundle contain different values for the colors, the default colors will be overwritten. So when no color is specified, the defaults will be used.

**Comment by timkoers** [comment]
@shliama It is fixed now!

**Pull request merged**
