### PR TITLE
Add round profile to crop.

### PR DESCRIPTION
**Pull request by hearsilent**

### CODE REVIEW

**Comment by loeschg** [comment]
Would love to have an oval cropping style!

**Comment by Rainer-Lang** [comment]
+1

**Comment by shliama** [comment]
Yes, round & oval cropping style option will be added soon.

But I cannot accept this pull request, because:
1. It has huge performance issues. You call drawRoundProfile() method for each frame drawn which in turn does tremendous amount of work (e.g. allocating memory for new objects). Please check out this video: https://www.youtube.com/watch?v=HAK5acHQ53E
2. Furthermore the result of what you try to accomplish doesn't look correct too.

Stay tuned for updates :radio:

**Comment by hearsilent** [comment]
@shliama 

Thanks for your suggestion.
1. I had commit code to fix it.
2. This pull request only show round profile preview for what apps wants show both round photo & rectangle photo.

https://github.com/hearsilent/uCrop/commit/ee4d2f6b7420495cc98c8515785c0a836652b5f9

If you think this commit is ok, I will open pull request again.

**Pull request closed without merging**
