### PR TITLE
Improve layout

### PR DESCRIPTION
**Pull request by hearsilent**
### Before
device-2019-04-11-174758

### After
device-2019-04-11-174704

### CODE REVIEW

**Comment by hearsilent** [comment]
@p1nkydev Can you review this? Thx :)

**Comment by p1nkydev** [comment]
@hearsilent Good job! Could you please create requests for native/non-native variants and I will merge it.

**Comment by hearsilent** [comment]
@p1nkydev But native/non-native are use the same layout

**Comment by p1nkydev** [comment]
@hearsilent I mean create, please, pull request to develop branch and feature/non-native.

**Comment by hearsilent** [comment]
@p1nkydev Got it!

**Comment by p1nkydev** [comment]
@hearsilent Thanks!

**Pull request merged**
