### PR TITLE
Remove synthetic accessor methods

### PR DESCRIPTION
**Pull request by liangricha**
These are created when private fields/methods from the outer class are accessed from an inner class.
This patch removes 11 methods from the uCrop and 2 methods from sample.

### CODE REVIEW

**Comment by shliama** [comment]
I don't think these changes will improve performance but definitely weaken encapsulation.

**Comment by Archinamon** [comment]
Synthetic reference to the enclosing class instance will be created anyway no matter what access modifiers you use. Making inner class static will deny synthetic access.
Just to clarify the behaviour. :)

**Comment by liangricha** [comment]
Hmm the dex method count definitely decreased when I changed the modifiers.

**Comment by Archinamon** [comment]
@liangricha yes, count will reduce because javac creates a nested inter-type accessor to the enclosing synthetic's private methods and fields. But escaping those accessors you won't negate synthetic instance linking on instantiation step.

**Comment by liangricha** [comment]
Ahh I see. Those accessors seem seem like they should be minimized though (especially for Android with limited resources/method limits). Although I realize doing so will weaken encapsulation.

**Pull request closed without merging**
